
'''
                This is a dummy file for translating Nemo Action files

                It was generated by the extract_action_strings script.
'''
                
90_new-launcher_nemo_action_in_Name = _("Create a new l_auncher here...")
90_new-launcher_nemo_action_in_Tooltip = _("Create a new launcher in this folder")
90_new-workspace_nemo_action_in_Name = _("Jump to new workspace")
90_new-workspace_nemo_action_in_Tooltip = _("Create a new workspace and activate it")
91_delete-workspace_nemo_action_in_Name = _("Remove workspace")
91_delete-workspace_nemo_action_in_Tooltip = _("Remove the currently active workspace")
92_show-expo_nemo_action_in_Name = _("Manage workspaces (Expo)")
92_show-expo_nemo_action_in_Tooltip = _("Open Expo to add, remove, or organize workspaces")
add-desklets_nemo_action_in_Name = _("Add Desklets")
add-desklets_nemo_action_in_Tooltip = _("Add Cinnamon desklets")
change-background_nemo_action_in_Name = _("Change Desktop _Background")
change-background_nemo_action_in_Tooltip = _("Change the Cinnamon desktop background")
mount-archive_nemo_action_in_Name = _("Mount archive")
mount-archive_nemo_action_in_Tooltip = _("Mount %f to browse its contents")
set-as-background_nemo_action_in_Name = _("Set as Wallpaper...")
set-as-background_nemo_action_in_Tooltip = _("Set the selected image as your Cinnamon desktop wallpaper")
set-resolution_nemo_action_in_Name = _("Display Settings")
set-resolution_nemo_action_in_Tooltip = _("Change the resolution")
