
'''
                This is a dummy file for translating Nemo Action files

                It was generated by the extract_action_strings script on 2018-02-04 17:35:21.470652 UTC.
'''
                
_90_new_workspace_nemo_action_in_Name = _("Jump to new workspace")
_90_new_workspace_nemo_action_in_Tooltip = _("Create a new workspace and activate it")
_91_delete_workspace_nemo_action_in_Name = _("Remove workspace")
_91_delete_workspace_nemo_action_in_Tooltip = _("Remove the currently active workspace")
_92_show_expo_nemo_action_in_Name = _("Manage workspaces (Expo)")
_92_show_expo_nemo_action_in_Tooltip = _("Open Expo to add, remove, or organize workspaces")
_add_desklets_nemo_action_in_Name = _("Add Desklets")
_add_desklets_nemo_action_in_Tooltip = _("Add Cinamon desklets")
_change_background_nemo_action_in_Name = _("Change Desktop _Background")
_change_background_nemo_action_in_Tooltip = _("Change the Cinnamon desktop background")
_desktop_settings_nemo_action_in_Name = _("Desktop _Settings")
_desktop_settings_nemo_action_in_Tooltip = _("Change how your desktop works")
_mount_archive_nemo_action_in_Name = _("Mount archive")
_mount_archive_nemo_action_in_Tooltip = _("Mount %f to browse its contents")
_new_launcher_nemo_action_in_Name = _("Create a new l_auncher here...")
_new_launcher_nemo_action_in_Tooltip = _("Create a new launcher in this folder")
_set_as_background_nemo_action_in_Name = _("Set as Wallpaper...")
_set_as_background_nemo_action_in_Tooltip = _("Set the selected image as your Cinnamon desktop wallpaper")
