
                This is a dummy file for translating Nemo Action files

                It was generated by the extract_action_strings script on 2013-08-22 20:32:55.245391 UTC.

                
new-launcher_nemo_action_in_Name = _("Create a new l_auncher here...")
new-launcher_nemo_action_in_Tooltip = _("Create a new launcher in this folder")
set-as-background_nemo_action_in_Name = _("Set as Wallpaper...")
set-as-background_nemo_action_in_Tooltip = _("Set the selected image as your desktop wallpaper")
add-desklets_nemo_action_in_Name = _("Add Desklets")
add-desklets_nemo_action_in_Tooltip = _("Open Cinnamon Settings to add desklets")
change-background_nemo_action_in_Name = _("Change Desktop _Background")
change-background_nemo_action_in_Tooltip = _("Open settings to allow you to select a different desktop background")
