
                This is a dummy file for translating Nemo Action files

                It was generated by the extract_action_strings script on 2013-10-12 23:47:13.061652 UTC.

                
mount-archive_nemo_action_in_Name = _("Mount archive")
mount-archive_nemo_action_in_Tooltip = _("Mount %f to browse its contents")
change-background_nemo_action_in_Name = _("Change Desktop _Background")
change-background_nemo_action_in_Tooltip = _("Change Desktop _Background")
set-as-background_nemo_action_in_Name = _("Set as Wallpaper...")
set-as-background_nemo_action_in_Tooltip = _("Set the selected image as your desktop wallpaper")
new-launcher_nemo_action_in_Name = _("Create a new l_auncher here...")
new-launcher_nemo_action_in_Tooltip = _("Create a new launcher in this folder")
add-desklets_nemo_action_in_Name = _("Add Desklets")
add-desklets_nemo_action_in_Tooltip = _("Add Desklets")
