.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH Nemo 1 "24 May 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
nemo \- the GNOME File Manager
.SH SYNOPSIS
.B nemo
.RI [ options ] " URIs" ...
.br
.SH DESCRIPTION
This manual page documents briefly the
.B nemo
command. This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
Nemo is the file manager for the GNOME desktop.
.br
.SH OPTIONS
Nemo follows the usual GNU command line syntax, with long options starting
with two dashes (`-'). A summary of options is included below.
.TP
.B \-c
.TP
.B \-\-check
Perform a quick set of self-check tests.
.TP
.B \-g
.TP
.B \-\-geometry=\fIGEOMETRY\fR
Create the initial window with the given geometry.
.TP
.B \-n
.TP
.B \-\-no-default-window
Only create windows for explicitly specified URIs.
.TP
.B \-\-no-desktop
Do not manage the desktop \(em ignore the preference set in the preferences
dialog.
.TP
.B \-q
.TP
.B \-\-quit
Quit Nemo.
.TP
.B \-\-help
Show a summary of options.
.TP
.B \-\-version
Show Nemo' version.
.TP
Other standard GNOME options not listed here are also supported.
.SH SEE ALSO
Nemo documentation can be found from the "Help" menu, or by pressing the
F1 key. Nemo also has a website at
http://www.gnome.org/projects/nemo/
.SH AUTHOR
This manual page was written by Takuo KITAME <kitame@debian.org> and Dafydd
Harries <daf@muse.19inch.net> for the Debian GNU/Linux system (but may be used
by others).
