.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH nemo-connect-server 1 "05 Jan 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
nemo-connect-server \- To Access a remote server
.SH SYNOPSIS
.B nemo-connect-server
.RI [ options ]
.RI [ URI ]
.SH DESCRIPTION
This manual page documents briefly the
.B nemo-connect-server
command.
.PP
Nemo Connect Server is the connection manager for the GNOME desktop.
.PP
You can use the file manager to access a remote server, be it an FTP site,
a Windows share, a WebDav server or an SSH server.
.SH OPTIONS
Nemo follows the usual GNU command line syntax, with long options starting
with two dashes (`-'). A summary of options is included below.
.TP
.B \-\-help
Show a summary of options.
.TP
.B \-\-version
Show version.
.TP
Other standard GNOME options not listed here are also supported.
.SH SEE ALSO
Nemo Connect Server documentation can be found from the "Help" menu, or by pressing the
F1 key. Nemo also has a website at http://www.gnome.org/projects/nemo/
.SH AUTHOR
This manual page was written by Julian Andres Klode <jak@jak-linux.org> for the
Debian GNU/Linux system (but may be used by others), based on a manpage by
Fernando Ribeiro <fernando@staff.nerdgroup.org>.
